<<<<<<< HEAD
api_url = "https://api-inference.huggingface.co/models/gianlab/swin-tiny-patch4-window7-224-finetuned-skin-cancer"
api_token = "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"
=======
api_token = "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"
api_url = "https://api-inference.huggingface.co/models/gianlab/swin-tiny-patch4-window7-224-finetuned-skin-cancer"
>>>>>>> 874e81e441f5f9d496219cd4e52ae86fce3af511
